### PR TITLE
Replaced centos by alpine to shrink the final image

### PR DESCRIPTION
**Pull request by cecton**
By using alpine we can save ~210 MB.

docker-cleanup 5.242 MB
meltwater/docker-cleanup 215.7 MB

### CODE REVIEW

**Comment by mikljohansson** [comment]
I tried to run the alpine version of docker-cleanup but it fails to start because alpine doesn't have /bin/bash as is used in the run.sh shebang. Unfortunately the run.sh script also includes some bashisms that fail when changing the shebang to /bin/sh

Perhaps you could have a look at converting the bash specific syntax to standard sh syntax and changing the shebang to /bin/sh so the script works in alpine?

Also, "FROM alpine" could perhaps be "FROM alpine:latest"?

Cheers, 
 Mikael

**Comment by cecton** [comment]
Oops! Maybe I installed it the first time when I tried. I'll fix that soon.

**Comment by cecton** [comment]
For some reason I can't execute the docker binary of the host. It says "not found" in sh and "No such file or directory" in bash. Of course the file is there, stat indicates me that the file is properly executable. So I really have no idea of what's going on. I imagine I badly tested the first time, that's my only guess.

On the other hand, I think it will be better to have docker in the image since we only use the client. This seems to work perfectly as long as you use the last version of Docker and you don't even have to mount the binary anymore:

Example:

``` bash
docker run --privileged \
    -v /run/docker.sock:/var/run/docker.sock \
    docker-cleanup
```

The final image size is now 47 MB tough. What's your opinion?

**Comment by mikljohansson** [comment]
Installing bash looks good, and nicely avoids having to fix the syntax.
Docker should really be mapped from the host though, mostly for api version
reasons.

It's likely you don't have the docker binary installed on the host in
/usr/bin/docker but perhaps e.g. in /usr/local/bin/docker.  So when docker
first sees "-v /usr/bin/docker:/usr/bin/docker:r" and /usr/bin/docker
doesn't exist on the host, it'll create an empty directory called
/usr/bin/docker/

It's a common gotcha that docker automagically creates host directories for
bind mounts if they don't already exist, I've gotten bit by the same thing
several times myself :)

Have a look to see if /usr/bin/docker/ is actually a directory on your
host. If so change the path to the actual binary, e.g. "-v
/usr/local/bin/docker:/usr/bin/docker:r"

Cheers,
Mikael

**Comment by mikljohansson** [comment]
Might want to clean out any metadata that apk downloads and caches as part of the same RUN instruction so it doesn't end up in the layer, but perhaps this isn't an issue on alpine (it is on e.g. centos and Ubuntu)

**Comment by cecton** [comment]
Here is what I get:

[1] [09:39:46] ~/r/docker-cleanup master > docker run -it -v
/run/docker.sock:/var/run/docker.sock -v /bin/docker:/usr/bin/docker
--entrypoint=/bin/bash docker-cleanup
bash-4.3# stat /usr/bin/docker
  File: /usr/bin/docker
  Size: 13444448        Blocks: 26264      IO Block: 4096   regular file
Device: 801h/2049d      Inode: 73330       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-06-06 09:38:47.000000000
Modify: 2015-05-14 15:35:42.000000000
Change: 2015-05-23 10:01:39.000000000

bash-4.3# /usr/bin/docker
bash: /usr/bin/docker: No such file or directory

But I think you're right about the API. It's best to have the client and
the server running the same API.

**Comment by mikljohansson** [comment]
It actually works fine for us with external docker binary and just installing bash into the alpine image, perhaps there's something odd in your docker setup? Running it on Ubuntu e.g. like 

```
 docker run -e CLEAN_PERIOD=1 -e DELAY_TIME=1 \
   -v /var/run/docker.sock:/var/run/docker.sock:rw \
   -v /usr/bin/docker:/usr/bin/docker:r meltwater/docker-cleanup:latest
```

Anyhow, I've committed the diff to master and the resulting image virtual size is just 7mb which is awfully sweet, thanks for your help in fixing this issue!

Cheers, 
 Mikael

**Pull request closed without merging**
